/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormeIzmena;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import projektni.zadatak.Klase.Datoteke;
import KlaseOsoba.Dolazak_Radnika;
import projektni.zadatak.Klase.Posao;
import KlaseOsoba.Radnik;
/**
 *
 * @author risti
 */
public abstract class Glavna_Forma_Izmena extends Glavna_Forma {
    
    public DefaultComboBoxModel popuni_listu_poslova(){
        ucitaj_podatke();
        String pomocnaLista[] = new String[poslovi.size()];
        for(int i = 0; i < poslovi.size(); i++)
        pomocnaLista[i] = poslovi.get(i).getNaziv();
        DefaultComboBoxModel model = new DefaultComboBoxModel<>(pomocnaLista);
        return model;
    }
    
    public DefaultComboBoxModel popuni_listu_radnika(){
        ucitaj_podatke();
        String pomocnaLista[] = new String[poslovi.size()];
        for(int i = 0; i < poslovi.size(); i++)
        pomocnaLista[i] = poslovi.get(i).getNaziv();
        DefaultComboBoxModel model = new DefaultComboBoxModel<>(pomocnaLista);
        return model;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
